### ISSUE TITLE
About zero shot on node classification task

### ISSUE THREAD

**Issue by W-rudder** [VITA-Group/LLaGA#11]
Hello, it's a great work for me! I am interested in the zero shot task on node classification task. Could you please provide the dataset used for this task? For instance, I' d like to know "NODE EMBEDDING+TEXT ATTRIBUTES" template for this task. Thank you very much!

**Comment by ChenRunjin** [comment]
Thank you for your interest. Regarding the "NODE EMBEDDING+TEXT ATTRIBUTES" template, you can utilize it by changing the task name from 'nc' to 'nctext'. For details on the specific format, please refer to the 'nctext' prompt in the eval_pretrain.py

**Comment by W-rudder** [comment]
> Thank you for your interest. Regarding the "NODE EMBEDDING+TEXT ATTRIBUTES" template, you can utilize it by changing the task name from 'nc' to 'nctext'. For details on the specific format, please refer to the 'nctext' prompt in the eval_pretrain.py

Thanks a lot! BTW, in the setting of "NODE EMBEDDING+TEXT ATTRIBUTES", does the training process use the same template as the task 'nctext'?

**Comment by ChenRunjin** [comment]
Hi, as outlined in Appendix B, we employ the node description task (i.e. 'nd' task) to train our model in a zero-shot setting for node classification. This task aims to build a relationship between node embeddings and the textual space.
