### ISSUE TITLE
Request for Missing Data Processing Code

### ISSUE THREAD

**Issue by studycell** [VITA-Group/LLaGA#12]
Hello, thank you very much for your work. I noticed that some data processing files are not provided when running the code, as mentioned in the picture. Could you provide the code to generate these files?

![image](https://github.com/user-attachments/assets/8206ff60-56bf-40db-8e6e-c1f130340e45)

**Comment by ChenRunjin** [comment]
Hi, the functions to generate node_sequence and embeddings is provided in utils/data_processing.py.
