### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ZhuYun97** [VITA-Group/LLaGA#14]
Hi team, thanks for this interesting work!

The JSONL file for node classification of the ogbn-arxiv dataset appears to be missing from the provided [link](https://utexas.app.box.com/s/i7y03rzm40xt9bjbaj0dfdgxeyjx77gb/folder/248590283574).

**Comment by ChenRunjin** [comment]
sorry for the late reply, can you try this link: https://utexas.box.com/s/ji4s7fojdsegtd4k6573fv06k0uz4fyj

**Comment by ZhuYun97** [comment]
Currently, there are only JSONL files available for link prediction, but there are no corresponding files for node classification, such as `sampled_2_10_train.jsonl`.

**Comment by ChenRunjin** [comment]
With the new links, do you still only see the link prediction file? I can see the node classification one in the updated link: https://utexas.box.com/s/ji4s7fojdsegtd4k6573fv06k0uz4fyj

**Comment by ChenRunjin** [comment]
I found that both the old and new links contain the node classification file from my side, but it's on the second page.
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/f5b06628-6e69-4d4d-aa59-c1793cf3d223">

**Comment by ZhuYun97** [comment]
Thanks for your help, I have found them in the second page.
