### ISSUE TITLE
Question about the choice of k value in Laplacian embedding

### ISSUE THREAD

**Issue by Syzseisus** [VITA-Group/LLaGA#25]
Thank you for your great work and open source!

I noticed that in the dataset directory, there are three different Laplacian embedding files:
- `laplacian_2_5.pt`
- `laplacian_2_10.pt`
- `laplacian_2_20.pt`

Could you explain:
1. What do these numbers represent in the file names? (e.g., what does `2_10` mean?)
2. I noticed that Laplacian Embedding can be implemented using PyTorch Geometric like this:
    ```python
    from torch_geometric.transforms import AddLaplacianEigenvectorPE

    # k: number of eigenvectors to use
    transform = AddLaplacianEigenvectorPE(k=8)
    data = transform(data)
    ```
    * Could you share:
      * Which k values did you use in LLaGA?
      * Did you use `PyTorch Geometric` or a different implementation?
      * Relationship between `k` and Graph Size (number of nodes)
        How did you determine the value `k` in relation to the number of nodes in your graphs?
        Did you use same `k` for every graphs or different values with respect to the number of nodes?
3. Which file is used as the default in your experiments, and what was the reasoning behind that choice?

Sincerely, Syzseisus

**Comment by ChenRunjin** [comment]
2_10 means the template shape, ( sample 2 hop neighbors and 10 for each hop), In our paper, we use 2_10 template, you may also use other shape

**Comment by Syzseisus** [comment]
Thanks a lot!
