### ISSUE TITLE
fifth parameter

### ISSUE THREAD

**Issue by shoyua** [VITA-Group/LLaGA#5]
# $5 = embedding e.g. simteg, sbert, roberta
There is a problem with the description of the fifth parameter for the two training scripts; this is actually the description for the sixth parameter. The fifth parameter does not appear to be used in the training scripts.

**Comment by ChenRunjin** [comment]
Sorry for the late reply, because I'm quite busy in the past few weeks.

Thanks for pointing it out, I have fixed it!
