### ISSUE TITLE
Neighborhood Detail Question

### ISSUE THREAD

**Issue by hxu105** [VITA-Group/LLaGA#6]
Howdy, thank you for providing this amazing work, I have a little question regarding the Neighborhood Detail template. As you describe in the paper 
![image](https://github.com/VITA-Group/LLaGA/assets/40327643/3bd18118-8e24-4058-b2da-47dc200604cc)

The Laplacian embeddings come from the tree adjacency matrix, and the tree is transformed from the original graph. Why not directly use the graph adjacency matrix to calculate the Laplacian embeddings? The difference will be missing [pad] token embeddings.

**Comment by ChenRunjin** [comment]
Yes, We indeed use Laplacian embeddings derived from our computational tree. I think the biggest problem of using Laplacian embeddings from original graph is the efficiency. Note that, we need to do SVD on adjacency matrix for computing laplacian embedding. For a large graph, performing SVD on the entire adjacency matrix is particularly challenging. If we were to compute Laplacian embeddings for each small subgraph, we would need to conduct SVD during each inference, which remains time-consuming. However, given that the structure of our computational tree is fixed and relatively small, we can afford to pre-compute the Laplacian embeddings for this structure just once, and it can be applied to all inference.
