### ISSUE TITLE
How to map the IDs in your released dataset to the original IDs?

### ISSUE THREAD

**Issue by twelfth-star** [VITA-Group/LLaGA#7]
Thank you for your excellent work.

I am trying to test some baseline models on the same data split as you. However, I noticed that you used a set of new IDs in the data files you published, such as in the file `edge_sampled_2_10_only_test.jsonl`. I would like to know how I can get the correspondence between the IDs you used and the original IDs in the dataset. For example, for the PubMed dataset, how can I map your IDs to the original PMIDs?

**Comment by ChenRunjin** [comment]
Hi, we follow Graph-LLM to process our data, you can refer to https://github.com/CurryTang/Graph-LLM/blob/master/data.py parse_pubmed() function to understand how to map  original IDs  with our ids.

**Comment by twelfth-star** [comment]
I see. Thank you for your kind reply!
