### ISSUE TITLE
Discrepancy between paper and code about LLM tuning

### ISSUE THREAD

**Issue by shoyua** [VITA-Group/LLaGA#9]
Hello,
In your paper, the parameters of the LLM remain fixed throughout the process. However, when looking into the code, it appears that the freeze_backbone is set to False by default. If my understanding is correct, this would imply that the LLM and the Projector could be tuned together, right?

**Comment by ChenRunjin** [comment]
No, the backbone will always remain frozen when `tune_mm_mlp_adapter` is set to True. In our `train.sh`, this parameter is consistently set to True. In this case, the `freeze_backbone` parameter is redundant. It was introduced in a previous version of the code and I have removed it. Thank you!

**Comment by shoyua** [comment]
Thank you for your clarification
